# Generated by Django 5.0 on 2023-12-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('telephone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=7)),
                ('country', models.CharField(choices=[('option1', 'India'), ('option2', 'US'), ('option3', 'Autralia')], max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
