# Generated by Django 5.0 on 2023-12-26 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourWheelerParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=200)),
                ('built_type', models.CharField(max_length=50)),
                ('passenger', models.CharField(max_length=50)),
                ('engine_type', models.CharField(choices=[('option1', 'Inline engine'), ('option2', 'Cylinder configuration'), ('option3', 'V engine'), ('option4', 'Diesel engine'), ('option5', 'Four'), ('option6', 'OPOC engine'), ('option7', 'Petrol engine'), ('option8', 'Single cylinder engine'), ('option9', 'Six-cylinder'), ('option10', 'Stroke engine'), ('option11', 'V8'), ('option12', 'Compression ignition'), ('option13', 'Electric motor'), ('option14', 'Straight-five engine'), ('option15', 'Gas engine')], max_length=50)),
                ('fuel_consumpsion', models.CharField(max_length=50)),
                ('alternate_fuel_consumption', models.CharField(default='NA', max_length=50)),
                ('environment_safety', models.CharField(max_length=50)),
                ('airbags_count', models.IntegerField(default=0)),
                ('infotainment_system', models.CharField(choices=[('option1', 'manual'), ('option2', 'touch')], max_length=50)),
                ('gears_type', models.CharField(max_length=50)),
                ('car_type', models.CharField(choices=[('option1', 'Sedan'), ('option2', 'SUV'), ('option3', 'Pickup'), ('option4', 'Wagon'), ('option5', 'Minivan'), ('option6', 'Sports car'), ('option7', 'Utility vehicle'), ('option8', 'MPV'), ('option9', 'MUV'), ('option10', 'Van'), ('option11', 'Electric'), ('option12', 'Hybrid')], max_length=50)),
                ('ADAS', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='id',
        ),
        migrations.AlterField(
            model_name='userregister',
            name='company_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ApplicationRegistration',
            fields=[
                ('model_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(choices=[('option1', 'TAC'), ('option2', 'CoP'), ('option3', 'Coc'), ('option4', 'R&D Certificate')], max_length=50)),
                ('vehicle_or_part', models.CharField(choices=[('option1', 'vehicle'), ('option2', 'part')], max_length=50)),
                ('vehicle_type', models.CharField(choices=[('option1', 'four wheeler'), ('option2', 'two wheeler')], max_length=50)),
                ('description', models.TextField()),
                ('specification', models.FileField(upload_to='document')),
                ('design', models.FileField(upload_to='design')),
                ('blueprint', models.FileField(upload_to='blueprint')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_type.userregister')),
            ],
        ),
    ]
