# Generated by Django 5.0 on 2023-12-26 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_type', '0002_fourwheelerparameter_remove_userregister_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourwheelerparameter',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_type.userregister'),
        ),
        migrations.AlterField(
            model_name='fourwheelerparameter',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_type.applicationregistration'),
        ),
    ]
