# Generated by Django 5.0 on 2024-01-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_type', '0005_alter_fourwheelerparameter_adas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='CIN_number',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
