# Generated by Django 5.0 on 2024-01-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_type', '0006_userregister_cin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourwheelerparameter',
            name='passenger',
            field=models.IntegerField(),
        ),
    ]
